package com.lanjiao.gym.dao;

import com.lanjiao.gym.entity.Opentime;

public interface OpentimeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opentime
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opentime
     *
     * @mbg.generated
     */
    int insert(Opentime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opentime
     *
     * @mbg.generated
     */
    int insertSelective(Opentime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opentime
     *
     * @mbg.generated
     */
    Opentime selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opentime
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Opentime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opentime
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Opentime record);
}