package com.lanjiao.gym.dao;

import com.lanjiao.gym.entity.Reservation;

public interface ReservationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservation
     *
     * @mbrg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservation
     *
     * @mbg.generated
     */
    int insert(Reservation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservation
     *
     * @mbg.generated
     */
    int insertSelective(Reservation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservation
     *
     * @mbg.generated
     */
    Reservation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Reservation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Reservation record);
}