package com.lanjiao.gym.dao;

import com.lanjiao.gym.entity.Time;

public interface TimeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time
     *
     * @mbg.generated
     */
    int insert(Time record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time
     *
     * @mbg.generated
     */
    int insertSelective(Time record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time
     *
     * @mbg.generated
     */
    Time selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Time record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Time record);
}